#!/usr/bin/env php
<?php
/**
 * This file is part of Composer Update Analyser package.
 *
 * @author Jean-Baptiste Nahan <814683+macintoshplus@users.noreply.github.com>
 * @copyright 2016-2019 - Jean-Baptiste Nahan
 * @license MIT
 */

require __DIR__.'/vendor/autoload.php';

use Mactronique\CUA\CuaApplication;

$application = new CuaApplication();
$application->run();
